name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        if: matrix.os == 'ubuntu-latest'
      - run: go test ./...
        if: matrix.os == 'windows-latest'
      - uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest'
